name: Build for Linux

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build for Linux
    # Sử dụng môi trường Ubuntu mới nhất để build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1. Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Bật caching cho npm

      # 3. Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Cài đặt các thư viện Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pynput pyinstaller

      # 5. Cài đặt các dependencies của Node.js
      - name: Install npm dependencies
        run: npm ci

      # 6. Tải và thiết lập FFmpeg
      # BƯỚC MỚI VÀ QUAN TRỌNG NHẤT
      - name: Download and set up FFmpeg
        run: |
          echo "Setting up FFmpeg for Linux..."
          mkdir -p binaries/linux
          curl -L -o ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
          mkdir -p temp_ffmpeg
          tar -xf ffmpeg.tar.xz -C temp_ffmpeg --strip-components=1
          find temp_ffmpeg -name 'ffmpeg' -type f -exec mv {} binaries/linux/ \;
          rm -rf temp_ffmpeg
          chmod +x binaries/linux/ffmpeg
          rm ffmpeg.tar.xz
          echo "FFmpeg setup complete."

      # 7. (Tùy chọn) Kiểm tra lại xem các file binary đã đúng vị trí chưa
      - name: Verify binaries are present
        run: |
          echo "--- Verifying binaries directory structure after download ---"
          ls -R binaries
          echo "--- Verifying python script ---"
          ls -R python

      # 8. Chạy lệnh build chính
      - name: Build application
        run: npm run build

      # 9. Tải lên artifact đã build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScreenAwesome-Linux-AppImage
          path: dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}