name: Build for Linux

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux AppImage
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image (dựa trên Dockerfile.ubuntu20.04)
      - name: Build Docker Image
        run: docker build -t my-build-env -f dockerfiles/Dockerfile.ubuntu20.04 .

      # 4. Run build bên trong container
      - name: Run Build inside Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app my-build-env bash -c "
            export DEBUG=electron-builder &&
            cd /app &&
            npm ci --force &&
            npm version ${{ github.ref_name }} --no-git-tag-version &&
            xvfb-run --auto-servernum npm run build -- --publish never
          "

      # 5. Upload release
      - name: Create Release and Upload AppImage
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*.AppImage
