name: 'Build for Linux'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4

      - name: '2. Setup Node.js environment'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: '3. Setup Python environment'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: '4. Install System Dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libx11-dev libxext-dev libpng-dev libxkbfile-dev

      - name: '5. Install Python Dependencies'
        run: |
          pip install pynput pyinstaller

      - name: '6. Install NPM Dependencies'
        run: npm install

      - name: '7. Build the Application'
        run: npm run build

      - name: '8. Upload AppImage to Release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/ScreenAwesome-${{ github.ref_name }}.AppImage
          asset_name: ScreenAwesome-${{ github.ref_name }}-linux-x86_64.AppImage
          asset_content_type: application/vnd.appimage