name: 'Build for Windows'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4

      - name: '2. Setup Node.js environment'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: '3. Setup Python environment'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: '4. Install FFmpeg'
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: '5. Install Python Dependencies'
        run: |
          pip install --no-cache-dir pynput pyinstaller

      - name: '6. Install NPM Dependencies'
        run: npm install

      - name: '7. Build the Application'
        run: npm run build

      - name: '8. Upload Installer to Release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/ScreenAwesome Setup ${{ github.ref_name }}.exe
          asset_name: ScreenAwesome-Setup-${{ github.ref_name }}-windows-x64.exe
          asset_content_type: application/vnd.microsoft.portable-executable